server:
  port: 8080
  servlet:
    context-path: /

spring:
  #redis配置信息
  redis:
    #redis 服务器地址
    host: 127.0.0.1
    #redis端口
    port: 6379
    #客户端超时时间单位是毫秒 默认是2000
    timeout: 5000
    #最大空闲数
    maxIdle: 20
    #连接池的最大数据库连接数
    maxActive: -1
    #控制一个pool可分配多少个jedis实例,用来替换上面的maxActive
    maxTotal: 100
    #最大建立连接等待时间。如果超过此时间将接到异常
    maxWaitMillis: -1

  #rabbitMq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///lc?serverTimezone=CST
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

picPath: E:\XXX\YYY\


aliyun:
  aaaa: aaaa
  bbbb: bbbb
  cccc: cccc
  dddd: dddd
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#查看sql语句
logging:
  level:
    com.lc.springdev.mapper: DEBUG
