server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///lc?serverTimezone=CST
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

picPath: E:\XXX\YYY\


aliyun:
  aaaa: aaaa
  bbbb: bbbb
  cccc: cccc
  dddd: dddd
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#查看sql语句
logging:
  level:
    com.lc.springdev.mapper: DEBUG
